github_checks:
  annotations: true
coverage:
  range: 90..100
  round: down
  precision: 2
comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  # after_n_builds: 1
  # behavior: default
  # require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: no       # [yes :: must have a head report to post]
codecov:
  bot: "Jonny"
